(part "430450627"
    (packageRef "4304506YY_6")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "430450627")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "430450627")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/43045-0627/molex")
    (property "Description" "Micro-Fit 3.0 Vertical Header, 3.00mm Pitch, Dual Row, 6 Circuits, with PCB Polarizing Peg, Glow-Wire Capable, Black")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/430450227_sd.pdf")
    (property "symbolName1" "430450627")
)
